"""Heuristic pattern and phrase catalogs for route scoring."""

HARD_PATTERNS = [
    # Architecture / system design
    r"\barchitect(ure|ing)?\b",
    r"\bsystem\s+design\b",
    r"\bhigh[- ]level\s+design\b",
    r"\bhld\b",
    r"\bdesign\s+doc\b",
    r"\badr\b",
    r"\btechnical\s+design\b",
    r"\bdomain\s+model\b",
    r"\bbounded\s+context\b",
    r"\bevent[- ]driven\b",
    r"\bmicroservice(s)?\b",
    r"\bmulti[- ]service\b",
    r"\bcross[- ]cutting\b",
    r"\bdistributed\s+system\b",
    r"\bcap\s+theorem\b",
    r"\bconsistency\s+model\b",
    r"\bsaga\s+pattern\b",
    r"\bcqrs\b",
    r"\bevent\s+sourcing\b",
    # Large refactors / migrations
    r"\brefactors?\b.*\b(entire|whole|across|system|codebase|monolith)\b",
    r"\b(entire|whole)\s+(codebase|module|service)\b.*\brefactor",
    r"\bmigrat(e|ion)\b",
    r"\bbackfill\b",
    r"\bschema\s+migration\b",
    r"\bzero[- ]downtime\b",
    r"\brolling\s+(deploy|upgrade)\b",
    r"\bstrangler\b",
    r"\blegacy\s+rewrite\b",
    # Concurrency / reliability
    r"\brace\s*condition\b",
    r"\bdeadlock\b",
    r"\blivelock\b",
    r"\bheisenbug\b",
    r"\bflaky\b",
    r"\bintermittent\s+(fail|failure|bug|test)\b",
    r"\bnon[- ]deterministic\b",
    r"\bthread[- ]safe(ty)?\b",
    r"\bconcurrency\s+bug\b",
    r"\bmemory\s+leak\b",
    r"\bgoroutine\s+leak\b",
    r"\bresource\s+leak\b",
    # Incidents / production
    r"\bproduction\s+(outage|incident|sev|down|p0|p1)\b",
    r"\bsev[- ]?[0-2]\b",
    r"\bp[01]\b",
    r"\bpostmortem\b",
    r"\broot\s+cause\b",
    r"\brca\b",
    r"\bincident\s+response\b",
    r"\bon[- ]call\b",
    r"\bpager(duty)?\b",
    # Security
    r"\bsecurity\s+audit\b",
    r"\bthreat\s+model\b",
    r"\bpen(etration)?\s+test\b",
    r"\bvulnerabilit(y|ies)\b",
    r"\bcve[- ]?\d",
    r"\bauth(entication|orization)?\s+(bypass|flaw|hole)\b",
    r"\binjection\s+attack\b",
    r"\bxss\b",
    r"\bcsrf\b",
    r"\bssrf\b",
    r"\brce\b",
    r"\bprivilege\s+escalat",
    r"\bsecrets?\s+leak\b",
    r"\bcompromised\s+(key|token|credential)\b",
    # Performance / deep analysis
    r"\bdeep\s+dive\b",
    r"\bperformance\s+profil",
    r"\bhot\s+path\b",
    r"\blatency\s+(regress|spike|p99|p95)\b",
    r"\bthroughput\b",
    r"\bflame\s*graph\b",
    r"\bo(ut)?\s*of\s*memory\b",
    r"\boom\b",
    r"\bcpu\s+bound\b",
    r"\bgc\s+pause\b",
    # Hard reasoning asks
    r"\breasoning_effort\b.*\b(high|xhigh)\b",
    r"\bthink\s+hard\b",
    r"\bthink\s+step[- ]by[- ]step\b",
    r"\bcomplex\s+bug\b",
    r"\bsubtle\s+bug\b",
    r"\bhard\s+(problem|bug|issue)\b",
    r"\bnon[- ]trivial\b",
    r"\binvestigate\s+(why|how|the)\b",
    r"\bwhy\s+does\s+this\s+(fail|break|flake)\b",
    r"\bcompare\s+trade[- ]?offs?\b",
    r"\btrade[- ]?off\s+analysis\b",
    r"\bprove\s+(correctness|safety)\b",
    r"\bformal\s+verif",
    r"\bconsensus\s+algorithm\b",
    r"\bpaxos\b",
    r"\braft\b",
]

MEDIUM_VERBS = [
    r"\bimplement\b",
    r"\bscaffold\b",
    r"\bwire\s+up\b",
    r"\badd\s+(?:an?\s+)?(?:[\w.-]+\s+){0,4}(feature|test|tests|endpoint|handler|component|route|api|hook|middleware|guard|dto|schema|migration|button|page|screen|form|modal|dialog)\b",
    r"\badd\s+(?:an?\s+)?(?:[\w.-]+\s+){0,4}unit\s+test\b",
    r"\bwrite\s+(?:an?\s+)?(?:[\w.-]+\s+){0,3}(test|tests|spec|specs|function|method|class|module|script)\b",
    r"\bgenerate\s+(?:an?\s+)?(?:[\w.-]+\s+){0,3}(test|boilerplate|stub|mock)\b",
    r"\bbuild\s+(?:an?\s+)?(?:[\w.-]+\s+){0,3}(feature|component|endpoint|page|api|service|module)\b",
    r"\bcreate\s+(?:an?\s+)?(?:[\w.-]+\s+){0,3}(feature|component|endpoint|page|api|service|module|test|tests|class|function|pytest|jest|vitest)\b",
    r"\bfix\s+(the\s+)?(bug|issue|error|failure|failing\s+test|npe|null\s*pointer|type\s*error|crash)\b",
    r"\bpatch\s+(the\s+)?(bug|issue|error|handler|endpoint)\b",
    r"\baddress\s+(the\s+)?(bug|issue|todo|failing)\b",
    r"\bupdate\s+(the\s+)?(code|logic|handler|endpoint|component|schema|deps|dependencies)\b",
    r"\bchange\s+(the\s+)?(behavior|logic|api|schema|implementation)\b",
    r"\bmodify\s+(the\s+)?(code|handler|component|function|method)\b",
    r"\bedit\s+(the\s+)?(file|component|function|handler)\b",
    r"\breplace\s+(the\s+)?(implementation|handler|component)\b",
    r"\bconvert\s+(to|into)\b",
    r"\bport\s+(to|from)\b",
    r"\bunit\s+test\b",
    r"\bintegration\s+test\b",
    r"\be2e\b",
    r"\bend[- ]to[- ]end\b",
    r"\bsnapshot\s+test\b",
    r"\brefactor\b",
    r"\bextract\b",
    r"\binline\b",
    r"\bclean\s+up\b",
    r"\boptimize\b",
    r"\bspeed\s+up\b",
    r"\benhance\b",
    r"\bintegrate\b",
    r"\bhook\s+into\b",
    r"\bset\s+up\b",
    r"\bsetup\b",
    r"\bconfig(ure)?\b",
    r"\bdeploy\b",
    r"\brollback\b",
    r"\bvalidate\b",
    r"\bsanitize\b",
    r"\bserialize\b",
    r"\bdeserialize\b",
]

# Stack/tech cues only count when a medium verb also matched.
MEDIUM_STACK = [
    r"\bcoverage\b",
    r"\bjest\b",
    r"\bpytest\b",
    r"\bvitest\b",
    r"\bplaywright\b",
    r"\bcypress\b",
    r"\bdry\b",
    r"\bapi\s+client\b",
    r"\bcrud\b",
    r"\bendpoint\b",
    r"\bcontroller\b",
    r"\bservice\s+layer\b",
    r"\brepository\b",
    r"\bprisma\b",
    r"\btypeorm\b",
    r"\bsqlalchemy\b",
    r"\bdjango\b",
    r"\bflask\b",
    r"\bfastapi\b",
    r"\bexpress\b",
    r"\bnext\.?js\b",
    r"\bsvelte\b",
    r"\btypescript\b",
    r"\beslint\b",
    r"\bprettier\b",
    r"\bgithub\s+actions?\b",
    r"\bdocker(file)?\b",
    r"\bkubernetes\b",
    r"\bk8s\b",
    r"\bhelm\b",
    r"\bterraform\b",
    r"\bgraphql\b",
    r"\brest\s+api\b",
    r"\bwebsocket\b",
    r"\boauth\b",
    r"\bjwt\b",
    r"\brbac\b",
    r"\bi18n\b",
    r"\blocalization\b",
    r"\ba11y\b",
    r"\baccessib(le|ility)\b",
    r"\bresponsiv(e|eness)\b",
    r"\btailwind\b",
    r"\bstyling\b",
    r"\bfrontend\b",
    r"\bbackend\b",
    r"\bfull[- ]?stack\b",
]

EASY_PATTERNS = [
    # Lookups / navigation
    r"\brename\b",
    r"\btypo\b",
    r"\bspelling\b",
    r"\bexplain\b",
    r"\bwhat\s+(is|does|are|was|were)\b",
    r"\bwhere\s+(is|are|was|were)\b",
    r"\bwhich\s+file\b",
    r"\bwho\s+(owns|wrote|calls)\b",
    r"\bhow\s+do\s+i\s+run\b",
    r"\bshow\s+me\b",
    r"\bfind\s+(the\s+)?(file|function|class|symbol|definition)\b",
    r"\bgo\s+to\b",
    r"\bopen\s+(the\s+)?file\b",
    r"\blist\s+(the\s+)?(files?|dirs?|directories|endpoints|routes|scripts)\b",
    r"\bls\b",
    r"\btree\b",
    r"\bpwd\b",
    r"\bprint\s+(the\s+)?(path|env|version)\b",
    # Light docs / formatting
    r"\bsummarize\b",
    r"\btldr\b",
    r"\beli5\b",
    r"\bformat\b",
    r"\bindent\b",
    r"\bwhitespace\b",
    r"\bcomment\b",
    r"\bdocstring\b",
    r"\bjsdoc\b",
    r"\bjavadoc\b",
    r"\breadme\b",
    r"\bchangelog\b",
    r"\btranslate\b",
    # Trivial / greeting / tiny edits
    r"\bsimple\b",
    r"\btrivial\b",
    r"\bquick\b",
    r"\bminor\b",
    r"\btiny\b",
    r"\bsmall\s+(change|edit|tweak)\b",
    r"\bping\b",
    r"\bhello\b",
    r"\bhi\b",
    r"\bthanks\b",
    r"\bthank\s+you\b",
    r"\bboilerplate\b",
    r"\bstub\b",
    r"\bnoop\b",
    r"\badd\s+a\s+(log|print|comment|todo|note)\b",
    r"\bremove\s+a\s+(log|print|comment|todo|note)\b",
    r"\bdelete\s+(the\s+)?(comment|log|print)\b",
    r"\bcapitalize\b",
    r"\blowercase\b",
    r"\buppercase\b",
    r"\btrim\b",
    r"\bsort\s+(the\s+)?(imports?|keys?)\b",
    r"\balphabetize\b",
    r"\bwrap\s+in\s+try\b",
    r"\badd\s+type\s+hint\b",
    r"\badd\s+types?\b",
    r"\bexport\s+(the\s+)?(type|interface|const)\b",
    r"\bimport\s+(path|statement)\b",
    r"\bfix\s+(the\s+)?(import|typo|indent|spacing|lint)\b",
]

# Difficulty cues that raise score (stay on auto ladder → sonnet + higher effort).
OPUS_HARD_PHRASES = [
    "multi service migration", "multiservice migration", "entire codebase",
    "whole codebase", "cross cutting", "cross-cutting", "distributed systems",
    "threat model", "security audit", "production outage", "root cause analysis",
    "deep dive into", "formal verification", "consensus",
]

FABLE_HARD_PHRASES = [
    "longest horizon", "maximum reasoning", "mythos",
    "hardest problem", "mission critical redesign", "company wide migration",
    "company-wide migration", "org wide architecture", "org-wide architecture",
]

# Explicit opt-in only — never inferred from difficulty alone.
OPT_IN_OPUS = [
    "use opus", "with opus", "ask opus", "via opus", "on opus",
    "force opus", "route opus", "switch to opus",
]

OPT_IN_FABLE = [
    "use fable", "with fable", "ask fable", "via fable", "on fable",
    "force fable", "route fable", "switch to fable",
]

# Back-compat names used elsewhere historically.
OPUS_PHRASES = OPUS_HARD_PHRASES
FABLE_PHRASES = FABLE_HARD_PHRASES

HARD_PHRASES = [
    "figure out why", "dig into why", "dig into how", "get to the bottom",
    "whats going wrong", "what's going wrong", "what is going wrong",
    "keeps failing intermittently", "fails randomly", "only fails sometimes",
    "make it scale", "needs to scale", "under load", "p99 latency",
    "security review", "lock down auth", "is this secure", "can this be exploited",
    "redesign the system", "rethink the architecture", "split into services",
    "data consistency", "eventual consistency", "exactly once", "at least once",
    "production is down", "site is down", "customers are blocked", "urgent outage",
    "racey", "heisenbug", "flakes in ci", "flake in ci", "ci is flaky",
    "memory keeps growing", "leaking memory", "oom killer",
    "tradeoffs between", "trade offs between", "pros and cons of adopting",
]

MEDIUM_PHRASES = [
    "can you add", "could you add", "please add", "pls add",
    "can you make", "could you make", "please make", "pls make",
    "can you fix", "could you fix", "please fix", "pls fix",
    "can you write", "could you write", "please write",
    "can you implement", "could you implement", "please implement",
    "whip up", "knock out a", "put together a", "throw together",
    "hook this up", "hook it up", "plug this in", "plug it in",
    "make a page", "make a form", "make a component", "make an endpoint",
    "make a test", "add tests for", "cover this with tests",
    "ship a", "land a pr for", "open a pr for",
    "update the logic", "tweak the behavior", "adjust the handler",
    "get this working", "make it work", "make this work",
    "drop in a", "slot in a",
]

EASY_PHRASES = [
    "what does this do", "whats this", "what's this", "what is this",
    "where does this live", "where is this defined", "point me to",
    "just wondering", "quick question", "one liner", "one-liner",
    "remind me", "refresh my memory", "in plain english", "in plain english",
    "too long didnt read", "too long didn't read",
    "say hi", "you there", "are you there",
    "fix spelling", "spelling mistake", "naming nit", "nit:",
]
